[package]
name = "espup"
version = "0.1.0"
authors = ["Sergio Gasquez Arcos <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/esp-rs/espup"
description = """
Tool for installing and maintaining ESP Rust environment.
"""
keywords = ["esp", "esp-rs", "embedded", "cli", "xtensa", "espidf"]
categories = ["command-line-utilities", "development-tools", "embedded"]

[dependencies]
anyhow = "*"
clap = { version = "4.0.15", features = ["derive"] }
dirs = "*"
flate2 = "1.0.22"
guess_host_triple = "0.1.3"
reqwest = { version = "0.11.12", features = ["blocking"] }
tar = "0.4.37"
zip = "*"
xz2 = "0.1.6"
console = "0.15.1"
tempfile = "3.3.0"
log = "0.4.17"
env_logger = "0.9.0"
embuild = { version = "0.30.4", features = ["espidf", "git"] }
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24.3"
toml = "0.5.9"
directories-next = "2.0.0"
serde = { version = "1.0.146", features = ["derive"] }
miette = "5.3.0"
regex = "1.6.0"

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.x86_64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[profile.release]
lto = "thin"
strip = true
