[package]
name = "esp-rs"
version = "0.1.0"
authors = ["Sergio Gasquez Arcos <sergio.gasquez@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "*"
clap = { version = "3.2", features = ["derive"] }
clap-nested = "*"
dirs = "*"
flate2 = "1.0.22"
git2 = "0.15.0"
guess_host_triple = "0.1.3"
json = "*"
md5 = "*"
num_cpus = "*"
reqwest = { version = "0.10.0-alpha.2", features = ["blocking"] }
tar = "0.4.37"
tokio = { version = "1.15.0", features = ["full"] }
walkdir = "*"
wmi = "*"
widestring = "1.0.2"
winapi = { version = "*", features = ["setupapi", "handleapi", "processthreadsapi", "winnt", "securitybaseapi", "impl-default", "shellapi", "winuser"] }
zip = "*"
xz2 = "0.1.6"

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"
