[package]
name = "espup"
version = "0.1.0"
authors = ["Sergio Gasquez Arcos <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/SergioGasquez/espup"
description = """
Tool for installing and maintaining ESP Rust toolchain.
"""
keywords = ["esp", "esp-rs", "embedded", "cli", "xtensa", "espidf"]
categories = ["command-line-utilities", "development-tools", "embedded"]

[dependencies]
anyhow = "*"
clap = { version = "3.2", features = ["derive"] }
clap-nested = "*"
dirs = "*"
flate2 = "1.0.22"
git2 = "0.15.0"
guess_host_triple = "0.1.3"
json = "*"
md5 = "*"
num_cpus = "*"
reqwest = { version = "0.11.12", features = ["blocking"] }
tar = "0.4.37"
tokio = { version = "1.15.0", features = ["full"] }
walkdir = "*"
wmi = "*"
widestring = "1.0.2"
winapi = { version = "*", features = [
    "setupapi",
    "handleapi",
    "processthreadsapi",
    "winnt",
    "securitybaseapi",
    "impl-default",
    "shellapi",
    "winuser",
] }
zip = "*"
xz2 = "0.1.6"
console = "0.15.1"
tempfile = "3.3.0"
clap-verbosity-flag = "1.0.1"
log = "0.4.17"
env_logger = "0.9.0"
embuild = { version = "0.30.3", features = ["espidf", "git"] }
strum = { version = "0.24", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"
